Fix : AttributeError
AttributeError: 'str' object has no attribute 'size' . 
Error was due to change in bert module. 
Hence adapted the change to current code